name: Publish to hex.pm

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish to Hex
        uses: erlangpack/github-action@v1
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
